// Labels mirror the source UI; effect values always come from jobtree.json.
export const EFFECT_TH = {
  attack: 'พลังโจมตี',
  damagePct: 'ดาเมจทุกแบบ %',
  attackDamagePct: 'ดาเมจสกิลโจมตี %',
  critMultPct: 'ความแรงคริ %',
  castSpeedPct: 'ความเร็วร่าย/โจมตี %',
  elementalDamagePct: 'ดาเมจธาตุ %',
  penetrationPct: 'เจาะเกราะ %',
  movementRechargePct: 'สกิลเคลื่อนที่ฟื้นไว %',
  manaCostReductionPct: 'ใช้ MP น้อยลง %',
  blockChancePct: 'โอกาสบล็อก %',
  goldFindPct: 'ทองที่ได้ %',
  materialFindPct: 'โอกาสได้วัตถุดิบ %',
  gearFindPct: 'โอกาสดรอปอุปกรณ์ %',
  magic: 'พลังเวท',
  defense: 'ป้องกัน',
  maxHp: 'HP',
  maxMp: 'MP',
  meleeDamagePct: 'ดาเมจประชิด %',
  projectileDamagePct: 'ดาเมจกระสุน %',
  areaDamagePct: 'ดาเมจวงกว้าง %',
  dotDamagePct: 'ดาเมจพื้นที่ต่อเนื่อง %',
  persistentDurationPct: 'ระยะเวลาพื้นที่คงอยู่ %',
  controlDurationPct: 'ระยะเวลาควบคุม/คำสาป %',
  spellDamagePct: 'ดาเมจเวท %',
  physicalDamagePct: 'ดาเมจกายภาพ %',
  fireDamagePct: 'ดาเมจไฟ %',
  coldDamagePct: 'ดาเมจน้ำแข็ง %',
  lightningDamagePct: 'ดาเมจสายฟ้า %',
  earthDamagePct: 'ดาเมจดิน %',
  poisonDamagePct: 'ดาเมจพิษ %',
  arcaneDamagePct: 'ดาเมจอาร์เคน %',
  summonDamagePct: 'ดาเมจอัญเชิญ %',
  maxHpPct: 'HP %',
  maxMpPct: 'MP %',
  barrierPct: 'เกราะเวท %',
  healPct: 'การฟื้นฟู %',
  moveSpeedPct: 'ความเร็วเดิน %',
  cooldownPct: 'คูลดาวน์เร็วขึ้น %',
  critChancePct: 'โอกาสคริ %',
  damageTakenPct: 'ดาเมจที่ได้รับ %',
  hpRegen: 'ฟื้น HP/วิ',
  mpRegenPct: 'ฟื้นมานา %',
  manaCostPct: 'ลดค่าใช้มานา %',
  projectileSpeedPct: 'ความเร็วกระสุน %',
  areaRadiusPct: 'รัศมีวงกว้าง %',
  echoDamagePct: 'ดาเมจ Echo %',
  extraMovementCharges: 'ชาร์จสกิลเคลื่อนที่',
  meleeHitBarrier: 'เกราะเมื่อตีประชิดโดน',
  healGrantsBarrierPct: 'ฮีลให้เกราะ %',
  meleeArcAdd: 'มุมฟัน°',
  poisonChancePct: 'โอกาสติดพิษ %',
  leechPct: 'ดูดเลือด %',
};
export function effectLabel(key) {return (EFFECT_TH[key] || key).replace(' %','');}
export function effectValue(key,value) {return `${value>0?'+':''}${Math.round(value*10)/10}${key.endsWith('Pct')?'%':''}`;}
export function effectText(key,value) {return `${effectLabel(key)} ${effectValue(key,value)}`;}
