// Real Game/Panels CSS touch-scroll regression: no WebGL dependency.
import{build}from'vite';import{chromium,webkit}from'playwright';import{readFileSync,writeFileSync,mkdirSync,existsSync}from'node:fs';import assert from 'node:assert/strict';
const engine=process.env.BROWSER==='webkit'?webkit:chromium,out=`tests/browser/out/details-touch-${engine.name()}`;mkdirSync(out,{recursive:true});
const result=await build({configFile:false,logLevel:'error',build:{write:false,minify:false,lib:{entry:new URL('./workspace-harness.js',import.meta.url).pathname,name:'DetailsRepro',formats:['iife']}}});const code=result[0].output.find(f=>f.type==='chunk').code;
const css=['style','ux','art','workspaces','minimal','journal','overlays','fieldhud','menus','fullscreen','skill-journal/journal','loadout-workspace'].map(n=>readFileSync('src/ui/'+n+'.css','utf8')).join('\n');const browser=await engine.launch({executablePath:engine===chromium?process.env.CHROMIUM_EXECUTABLE:undefined,args:engine===chromium?['--no-sandbox']:[]});const results=[];
try{for(const [width,height]of [[1180,820],[844,390]]){
 const page=await browser.newPage({viewport:{width,height},hasTouch:true,isMobile:true});await page.route('http://details.local/**',async route=>{const u=new URL(route.request().url());if(u.pathname==='/')return route.fulfill({contentType:'text/html',body:'<!doctype html><html lang="th"><meta name="viewport" content="width=device-width,initial-scale=1"><body><div id="hud"></div></body></html>'});const f=new URL('../../public/'+u.pathname.slice(1),import.meta.url);return existsSync(f)?route.fulfill({path:f.pathname}):route.fulfill({status:404,body:''});});await page.goto('http://details.local/');await page.addStyleTag({content:css});await page.addScriptTag({content:code});await page.evaluate(()=>{const f=window.__frontier,g=f.game;g.ch.gold=1000;g.ch.materials.enhancement_stone=16;[g.player.x,g.player.z]=g.data.world.town.workbench;f.panels.open('bag');});await page.locator('#atelier [data-action=details]').tap();
 const read=()=>page.evaluate(()=>{const d=document.querySelector('.atelier-dialog'),b=d.querySelector('[data-action=cancel]'),r=d.getBoundingClientRect(),br=b.getBoundingClientRect();const x=r.x+r.width*.4,y=r.y+r.height*.65,t=document.elementFromPoint(x,y);return {top:d.scrollTop,scrollHeight:d.scrollHeight,clientHeight:d.clientHeight,closeVisible:br.top>=0&&br.bottom<=innerHeight,point:{x,y},target:t?.tagName,touchAction:t&&getComputedStyle(t).touchAction,inert:!!d.closest('[inert]'),fullscreenBlocked:document.body.classList.contains('fullscreen-blocked')};});
 const before=await read();assert.ok(before.closeVisible,'Close is accessible without scrolling');assert.equal(before.inert,false);assert.equal(before.touchAction,'pan-y');const summary=page.locator('.detail-upgrade-summary');assert.match(await summary.innerText(),/หินเสริมอุปกรณ์/);assert.match(await summary.innerText(),/16\s*\/\s*1/);assert.match(await summary.innerText(),/1,000\s*\/\s*35/);assert.match(await summary.innerText(),/พร้อมอัปเกรด/);const cdp=engine===chromium?await page.context().newCDPSession(page):null,start=before.point;if(cdp){await page.evaluate(()=>{window.__detailsScrolling=true;document.querySelector('.atelier-dialog').addEventListener('scrollend',()=>window.__detailsScrolling=false,{once:true});});await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...start,id:1}]});for(let i=1;i<=7;i++){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:start.x,y:start.y-i*30,id:1}]});await page.waitForTimeout(30);}await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForTimeout(100);}else await page.locator('.atelier-dialog').evaluate(d=>d.scrollTop=250);const after=await read();assert.ok(after.top>before.top+50,'details content scrolls');assert.ok(after.closeVisible,'Close remains accessible after scrolling');if(cdp)await page.waitForFunction(()=>window.__detailsScrolling===false);await page.screenshot({path:`${out}/details-${width}-after-swipe.png`});
 await page.locator('.atelier-dialog [data-action=cancel]').tap();console.log('first close',width,await page.locator('.dialog-backdrop').count());assert.equal(await page.locator('.dialog-backdrop').count(),0);results.push({width,height,before,after,closeAfterScroll:await page.locator('.atelier-dialog').count()===0});for(const entry of ['bag','equipped','workbench'])for(let i=0;i<2;i++){
 await page.evaluate(entry=>{const f=window.__frontier,g=f.game,p=f.panels;p.close();
  if(entry==='workbench'){
   const rid=Object.entries(g.data.recipes.recipes).find(([,r])=>r.type==='gear'&&r.result==='tusk_blade')[0];
   if(!g.ch.gear.some(it=>it.uid===999))g.ch.gear.push({uid:999,base:'tusk_blade',itemLevel:g.data.items.gearBases.tusk_blade.itemLevel,grade:'C',upgrade:0,options:[]});
   p.sel.craftRecipe=rid;p.sel.craftHistory={[rid]:[999]};p.open('craft');
  }else p.open('bag');
 },entry);
 if(entry==='workbench')await page.locator('[data-act=inspect-crafted][data-uid="999"]').tap();
 else if(entry==='equipped')await page.locator('#atelier .wear-weapon').tap();
 else await page.locator('#atelier [data-action=item][data-id="1"]').tap();
 await page.locator('#atelier [data-action=details]').tap();
 assert.equal(await page.locator('[data-act=gear-up]').getAttribute('data-uid'),entry==='workbench'?'999':'1');
 await page.locator('.atelier-dialog [data-action=cancel]').tap();assert.equal(await page.locator('.dialog-backdrop').count(),0);
 if(entry==='workbench'){await page.locator('[data-action=return-craft]').tap();assert.equal(await page.evaluate(()=>__frontier.panels.tab),'craft');}
 console.log('PASS details path',width,entry,i);
}
await page.evaluate(()=>{__frontier.panels.close();__frontier.panels.open('bag');});await page.locator('#atelier [data-action=item][data-id="1"]').tap();await page.locator('#atelier [data-action=details]').tap();await page.locator('[data-act=gear-up]').tap();assert.equal(await page.evaluate(()=>__frontier.game.ch.gear[0].upgrade),1);assert.equal(await page.evaluate(()=>__frontier.game.ch.materials.enhancement_stone),15);assert.equal(await page.evaluate(()=>__frontier.game.ch.gold),965);await page.locator('.atelier-dialog [data-action=cancel]').tap();await page.evaluate(()=>{const f=window.__frontier;f.panels.close();f.game.player.x+=10;f.panels.open('bag');});await page.locator('#atelier [data-action=details]').tap();assert.match(await page.locator('[data-upgrade-status]').innerText(),/ต้องอยู่ใกล้โต๊ะคราฟต์/);assert.equal(await page.locator('[data-act=gear-up]').isDisabled(),true);assert.doesNotMatch(await page.locator('.upgrade-cost').innerText(),/พร้อมอัปเกรด/);await page.locator('.atelier-dialog [data-action=cancel]').tap();await page.close();
}writeFileSync(`${out}/result.json`,JSON.stringify({engine:engine.name(),scroll:engine===chromium?'native touch swipe':'WebKit DOM scroll plus descendant touch-action contract',results},null,2));console.log('PASS details touch',engine.name());}finally{await browser.close();}
