// Full game, persisted save, hit-tested touch controls; no preview renderer or UI harness.
import assert from 'node:assert/strict';
import {chromium,webkit} from 'playwright';
import fs from 'node:fs/promises';
import {loadoutCharacter} from './loadout-fixture.mjs';
import {freezeScene} from './freeze-scene.mjs';
const engineName=process.env.BROWSER||'chromium',engine=engineName==='webkit'?webkit:chromium;
const origin=process.env.UI_ORIGIN||'http://127.0.0.1:4186',out=process.env.UI_OUT||'evidence/ui-live';
await fs.mkdir(out,{recursive:true});
const browser=await engine.launch({executablePath:engine===chromium?process.env.CHROMIUM_EXECUTABLE||'/usr/bin/chromium':undefined,args:engine===chromium?['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']:[]});
const interactionViewport=process.env.UI_DEVICE==='tablet'?{width:1180,height:820}:{width:844,height:390};
const context=await browser.newContext({viewport:interactionViewport,hasTouch:true,isMobile:true,deviceScaleFactor:1});
const character=loadoutCharacter(),slot2=JSON.stringify({version:2,character:{...character,name:'Untouched slot 2'}});
await context.addInitScript(({character,slot2})=>{
 // Exercise the supported fallback path rather than depend on headless fullscreen.
 Object.defineProperty(document,'fullscreenEnabled',{value:false,configurable:true});
 if(!localStorage.getItem('loadout-test-initialized')){
  localStorage.setItem('frontier.slot.1',JSON.stringify({version:2,character}));localStorage.setItem('frontier.lastSlot','1');localStorage.setItem('frontier.slot.2',slot2);localStorage.setItem('frontier-demo.save.v1','legacy sentinel');localStorage.setItem('loadout-test-initialized','yes');
 }
},{character,slot2});
const page=await context.newPage(),errors=[],checks=[],geometry=[];page.setDefaultTimeout(180000);
await page.route('**/favicon.ico',route=>route.fulfill({status:204}));
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
const tap=async selector=>{
 if(/data-action=["'](?:item|mod|skill)["']/.test(selector)&&!(await page.locator(selector).count())){
  for(let i=0;i<8&&!(await page.locator('#atelier [data-action="prev"]').isDisabled());i++)await page.locator('#atelier [data-action="prev"]').tap();
  for(let i=0;i<8&&!(await page.locator(selector).count())&&!(await page.locator('#atelier [data-action="next"]').isDisabled());i++)await page.locator('#atelier [data-action="next"]').tap();
 }
 await page.locator(selector).tap();
};
const check=async(label,run)=>{await run();checks.push(label);console.log('PASS '+label)};
const settled=()=>page.waitForFunction(()=>document.querySelectorAll('.flying-coin,.arriving,.seated').length===0,null,{timeout:3000});
const state=()=>page.evaluate(()=>{const f=__frontier;return {ui:f.panels.loadout.state,slots:structuredClone(f.game.ch.slots),mods:structuredClone(f.game.ch.mods),gear:structuredClone(f.game.ch.gear),equipped:{...f.game.ch.equipped},save:JSON.parse(localStorage.getItem('frontier.slot.1')).character}});
const mod=async id=>{const uid=await page.evaluate(id=>__frontier.game.ch.mods.find(m=>m.id===id).uid,id);await tap(`#atelier [data-action="mod"][data-id="${uid}"]`);return uid;};
const open=async tab=>{await page.evaluate(tab=>__frontier.panels.open(tab),tab);};
const ready=async()=>{await page.waitForFunction(()=>__frontier?.modelsReady&&__frontier?.game);await page.evaluate(()=>document.fonts.ready);await page.waitForFunction(()=>getComputedStyle(document.getElementById('loading')).opacity==='0');await page.evaluate(()=>window.__loadoutReviewDraw=__frontier.view.render.bind(__frontier.view));if(engineName!=='webkit')await freezeScene(page);};
const boot=async()=>{await page.goto(origin+'/?quality=high&seed=701&dynres=0&stream=0');await page.waitForFunction(()=>window.__frontier?.menu);if(await page.locator('.fullscreen-gate').isVisible())await tap(await page.locator('.fullscreen-fallback').isVisible()?'.fullscreen-fallback':'.fullscreen-enter');await tap('[data-act="continue"]');await ready();};
try {
 await boot();
 const anchors=await page.locator('.pframe,.quick-actions,.sbtn').evaluateAll(els=>els.map(e=>{const r=e.getBoundingClientRect();return [r.x,r.y,r.width,r.height]}));
 await tap('.quick-actions [aria-label="กระเป๋า"]');await page.waitForSelector('#atelier .hero-art');
 await check('normal bag opens the two windows with actual saved character',async()=>{assert.equal(await page.locator('.character-caption h2').innerText(),'Aerin');assert.equal((await page.locator('.character-level').innerText()).trim(),'Lv. 12');assert.equal((await state()).mods.length,character.mods.length);assert.equal(await page.locator('.overlay.is-atelier.on').count(),1);assert.equal(await page.locator('.panel').isVisible(),false);});
 await check('MP formatting preserves the actual fractional skill cost',async()=>{const value=await page.evaluate(()=>({raw:__frontier.game.skills[2].cost,label:__frontier.input.buttons[2].querySelector('.skill-cost').textContent,accessible:__frontier.input.buttons[2].getAttribute('aria-label')}));assert.equal(value.raw,6.300000000000001);assert.equal(value.label,'6.3 MP');assert.ok(value.accessible.includes('6.3 MP'));assert.ok(!value.accessible.includes('000000'));});
 await check('gear cells use the authored grade palette and persistent item progression level',async()=>{const cells=await page.locator('.bag-grid [data-grade]').evaluateAll(es=>es.map(e=>({grade:e.dataset.grade,color:getComputedStyle(e).getPropertyValue('--grade-color').trim(),background:getComputedStyle(e).borderTopColor})));const palette=await page.evaluate(()=>__frontier.game.data.items.grades.colors);for(const cell of cells)assert.equal(cell.color,palette[cell.grade]);assert.ok(new Set(cells.map(c=>c.background)).size>=3);const snapshot=await state(),selected=snapshot.gear.find(i=>i.uid===snapshot.ui.selected);assert.equal(await page.locator('.selection-shelf [data-item-level]').innerText(),'Lv. '+selected.itemLevel);assert.ok((await state()).gear.every(i=>Number.isInteger(i.itemLevel)&&i.itemLevel>0));});
 await check('browsing/filtering/details preserves character state',async()=>{const before=await state();await page.locator('#atelier [data-filter]').selectOption('boots');await page.locator('#atelier [data-filter]').selectOption('all');await tap('#atelier [data-action="details"]');await tap('.atelier-dialog [data-action="cancel"]');const after=await state();assert.deepEqual(after.slots,before.slots);assert.deepEqual(after.equipped,before.equipped);assert.deepEqual(after.gear,before.gear);});
 await check('worn-slot selection clears an incompatible inventory filter',async()=>{await page.locator('#atelier [data-filter]').selectOption('weapon');const uid=character.equipped.helm;await tap(`[data-action="wear"][data-id="${uid}"]`);assert.equal((await state()).ui.selected,uid);assert.equal(await page.locator(`[data-action="item"][data-id="${uid}"].selected`).count(),1);});
 await check('external selection and viewport change keep the selected dense-page item and modal reachable',async()=>{
  const uid=await page.evaluate(()=>{const f=__frontier,ch=f.game.ch;window.__paginationProbe={gear:structuredClone(ch.gear),nextUid:ch.nextUid};for(let i=0;i<50;i++)ch.gear.push({...structuredClone(ch.gear[14]),uid:ch.nextUid++});const uid=ch.gear[35].uid;f.panels.sel.item=String(uid);f.panels.open('bag');return uid;});
  assert.equal((await state()).ui.page,Math.floor(35/(interactionViewport.height<=520?10:12)));assert.equal(await page.locator(`[data-action="item"][data-id="${uid}"].selected`).count(),1);
  await tap('#atelier [data-action="details"]');await page.setViewportSize({width:1180,height:820});await page.waitForFunction(()=>document.querySelector('.bag-grid').dataset.pageSize==='12');assert.equal(await page.locator('.atelier-dialog').isVisible(),true);
  await page.setViewportSize({width:844,height:390});await page.waitForFunction(()=>document.querySelector('.bag-grid').dataset.pageSize==='10');assert.equal(await page.locator('.atelier-dialog').isVisible(),true);await tap('.atelier-dialog [data-action="cancel"]');assert.equal(await page.locator(`[data-action="item"][data-id="${uid}"].selected`).count(),1);
  await page.setViewportSize(interactionViewport);await page.evaluate(()=>{const f=__frontier,ch=f.game.ch;Object.assign(ch,__paginationProbe);delete window.__paginationProbe;f.game.refresh();f.panels.sel.item=String(ch.gear[0].uid);f.panels.open('bag');});
 });
 await check('real equip saves immediately and updates full-body image',async()=>{const uid=character.gear.find(i=>i.base==='tusk_blade').uid;await tap(`[data-action="item"][data-id="${uid}"]`);const image=await page.locator('.hero-art').getAttribute('src');await tap('#atelier [data-action="equip"]:enabled');const after=await state();assert.equal(after.equipped.weapon,uid);assert.equal(after.save.equipped.weapon,uid);await page.waitForFunction(image=>document.querySelector('.hero-art')?.src!==image,image);assert.ok(await page.locator('.hero-art').isVisible());assert.equal(after.gear.length,character.gear.length);});
 await check('non-weapon remove retains owned item and saved UID',async()=>{const before=await state(),uid=before.equipped.helm;await tap(`[data-action="wear"][data-id="${uid}"]`);await tap('#atelier [data-action="equip"]:enabled');const after=await state();assert.equal(after.equipped.helm,null);assert.ok(after.gear.some(i=>i.uid===uid));assert.equal(after.save.equipped.helm,null);});
 await check('original upgrade handler remains available through details',async()=>{await tap('#atelier [data-action="details"]');const uid=(await state()).ui.selected,before=(await state()).gear.find(i=>i.uid===uid).upgrade;await tap(`.atelier-dialog [data-act="gear-up"][data-uid="${uid}"]`);assert.equal((await state()).gear.find(i=>i.uid===uid).upgrade,before+1);assert.equal((await state()).save.gear.find(i=>i.uid===uid).upgrade,before+1);await tap('.atelier-dialog [data-action="cancel"]');});
 await check('material details retain real sources and sale handler',async()=>{await tap('[data-action="bag-category"][data-id="material"]');await tap('[data-action="material"][data-id="boar_hide"]');await tap('#atelier [data-action="details"]');assert.match(await page.locator('.atelier-dialog').innerText(),/ใช้คราฟต์/);const n=await page.evaluate(()=>__frontier.game.ch.materials.boar_hide);await tap('.atelier-dialog [data-act="sell"][data-id="boar_hide"]');assert.equal(await page.evaluate(()=>__frontier.game.ch.materials.boar_hide),n-1);await tap('.atelier-dialog [data-action="cancel"]');});
 await open('mods');await tap('[data-action="slot"][data-id="2"]');await mod('burning_ground');
 await check('mod names use persistent grades while coin ability colors remain semantic',async()=>{const colors=[],names=[],savedPage=(await state()).ui.page;
  while(!(await page.locator('#atelier [data-action="prev"]').isDisabled()))await tap('#atelier [data-action="prev"]');
  for(;;){colors.push(...await page.locator('.mod-grid .coin').evaluateAll(es=>es.map(e=>({id:e.dataset.modId,role:e.className}))));names.push(...await page.locator('.mod-name[data-grade]').evaluateAll(es=>es.map(e=>({grade:e.dataset.grade,color:getComputedStyle(e).getPropertyValue('--grade-color').trim()}))));if(await page.locator('#atelier [data-action="next"]').isDisabled())break;await tap('#atelier [data-action="next"]');}
  while((await state()).ui.page>savedPage)await tap('#atelier [data-action="prev"]');
  assert.ok(colors.some(c=>c.id==='concentrated'&&c.role.includes('power')));assert.ok(colors.some(c=>c.id==='life_leech'&&c.role.includes('support')));assert.ok(colors.some(c=>c.id==='burning_ground'&&c.role.includes('mechanic')));const palette=await page.evaluate(()=>__frontier.game.data.items.grades.colors);assert.ok(names.length>=character.mods.length);for(const n of names)assert.equal(n.color,palette[n.grade]);assert.ok((await state()).mods.every(m=>['C','B','A','S'].includes(m.grade)));});
 await check('full replacement can be cancelled without a save mutation',async()=>{const before=await state();await tap('#atelier [data-action="apply"]');assert.equal(await page.locator('.replace-coins button').count(),2);await page.keyboard.press('Escape');assert.deepEqual((await state()).slots,before.slots);assert.deepEqual((await state()).save.slots,before.save.slots);assert.equal(await page.locator('#atelier').isVisible(),true);});
 await check('replacement ejects and inserts, then saves persistent attachment',async()=>{await tap('#atelier [data-action="apply"]');await tap('[data-action="replace-mod"][data-index="1"]');assert.equal(await page.locator('.flying-coin').count(),2);await page.evaluate(()=>__frontier.panels.render());await page.waitForTimeout(180);assert.ok(await page.locator('.flying-coin').count()>0,'same-state refresh preserves flight');const s=await state(),uid=s.ui.modUid;assert.ok(s.slots[2].mods.includes(uid));assert.deepEqual(s.save.slots,s.slots);await settled();assert.equal(await page.locator('.flying-coin').count(),0);assert.equal(await page.locator(`[data-target="2"] .socket[data-uid="${uid}"].linked`).count(),1);});
 await check('remove returns owned coin and rapid taps keep latest state',async()=>{const uid=(await state()).ui.modUid;await tap('#atelier [data-action="apply"]');assert.ok(!(await state()).slots.some(s=>s.mods.includes(uid)));for(let i=0;i<3;i++)await tap('#atelier [data-action="apply"]');assert.ok((await state()).slots[2].mods.includes(uid));await settled();assert.equal(await page.locator('.flying-coin,.arriving').count(),0);assert.equal((await state()).mods.length,character.mods.length);assert.deepEqual((await state()).save.slots,(await state()).slots);});
 await check('Escape cancels active flight without settings leakage',async()=>{await tap('#atelier [data-action="apply"]');await page.keyboard.press('Escape');assert.equal(await page.locator('.flying-coin').count(),0);assert.equal(await page.locator('#atelier').isVisible(),true);assert.notEqual(await page.evaluate(()=>__frontier.panels.tab),'settings');});
 await check('invalid compatibility never mutates or saves slots',async()=>{await mod('spiked_ward');const before=await state();await tap('#atelier [data-action="apply"]');assert.match(await page.locator('.atelier-notice').innerText(),/ขาดประเภท|เกราะ|รูปแบบการร่าย/);assert.deepEqual((await state()).slots,before.slots);assert.deepEqual((await state()).save.slots,before.save.slots);});
 await check('completed invalid feedback releases Escape to close the workspace',async()=>{await page.waitForFunction(()=>!__frontier.panels.loadout.state.moving,null,{timeout:3000});assert.equal((await state()).ui.moving,false);await page.keyboard.press('Escape');assert.equal(await page.locator('#atelier').isVisible(),false);await open('mods');await tap('[data-action="slot"][data-id="2"]');});
 await check('compatible stat-gated coin remains attached and inactive',async()=>{const uid=await mod('cast_on_dodge');await tap('#atelier [data-action="apply"]');await page.waitForTimeout(1000);assert.ok((await state()).slots[2].mods.includes(uid));assert.equal(await page.locator(`.socket[data-uid="${uid}"].inactive`).count(),1);assert.match(await page.locator('.shelf-actions').innerText(),/AGI/);});
 await check('reduced motion commits with no ghosts',async()=>{await page.emulateMedia({reducedMotion:'reduce'});await tap('#atelier [data-action="apply"]');assert.equal(await page.locator('.flying-coin,.arriving').count(),0);await page.emulateMedia({reducedMotion:'no-preference'});});
 await check('duplicate owned mod instances paginate without overflow',async()=>{while(!(await page.locator('#atelier [data-action="prev"]').isDisabled()))await tap('#atelier [data-action="prev"]');const capacity=interactionViewport.height<=520?6:12;assert.equal(await page.locator('.coin-cell').count(),capacity);await tap('#atelier [data-action="next"]');assert.equal(await page.locator('.coin-cell').count(),Math.min(capacity,character.mods.length-capacity));await tap('#atelier [data-action="prev"]');});
 await open('skills');
 await check('opening skills aligns library selection with the current equipped slot',async()=>{const s=await state();assert.equal(s.ui.skillId,s.slots[s.ui.slot].skill);assert.equal(await page.locator(`[data-action="skill"][data-id="${s.ui.skillId}"].selected`).count(),1);});
 await tap('[data-action="slot"][data-id="2"]');await tap('[data-action="skill"][data-id="slash"]');
 await check('skill swap carries the entire socket set after confirmation',async()=>{const before=await state();await tap('#atelier [data-action="apply"]');await tap('.atelier-dialog [data-action="confirm"]');const after=await state();assert.deepEqual(after.slots[2],before.slots[0]);assert.deepEqual(after.slots[0],before.slots[2]);assert.deepEqual(after.save.slots,after.slots);});
 await check('skill removal returns its coins to available ownership',async()=>{await tap('#atelier [data-action="apply"]');await tap('.atelier-dialog [data-action="confirm"]');assert.equal((await state()).slots[2].skill,null);assert.equal((await state()).slots[2].mods.length,0);assert.equal((await state()).mods.length,character.mods.length);});
 await check('unlearned movement rejection preserves current charges and save',async()=>{await tap('.category-tabs [data-action="category"][data-id="movement"]');await tap('[data-action="skill"][data-id="blink"]');const before=await page.evaluate(()=>({movement:__frontier.game.ch.movement,charges:__frontier.game.player.movement.charges}));await tap('#atelier [data-action="apply"]');assert.deepEqual(await page.evaluate(()=>({movement:__frontier.game.ch.movement,charges:__frontier.game.player.movement.charges})),before);});
 await check('accepted SkillTree remains reachable without workspace styles',async()=>{const before=await page.evaluate(()=>[...__frontier.game.ch.jobNodes]);await page.keyboard.press('j');assert.equal(await page.locator('.skill-journal').count(),1);assert.equal(await page.locator('#atelier').isVisible(),false);assert.equal(await page.locator('.overlay.is-atelier').count(),0);assert.deepEqual(await page.evaluate(()=>__frontier.game.ch.jobNodes),before);});
 await check('close resumes simulation and preserves HUD positions',async()=>{await open('bag');await tap('#atelier [data-action="close"]');const time=await page.evaluate(()=>__frontier.game.time);await page.waitForFunction(time=>__frontier.game.time>time,time,{timeout:3000});assert.ok(await page.evaluate(time=>__frontier.game.time>time,time));assert.deepEqual(await page.locator('.pframe,.quick-actions,.sbtn').evaluateAll(els=>els.map(e=>{const r=e.getBoundingClientRect();return [r.x,r.y,r.width,r.height]})),anchors);});
 await check('reload through Continue restores real equipped/loadout save',async()=>{const before=(await state()).save;await boot();assert.deepEqual((await state()).equipped,before.equipped);assert.deepEqual((await state()).slots,before.slots);assert.equal(await page.evaluate(()=>localStorage.getItem('frontier.slot.2')),slot2);assert.equal(await page.evaluate(()=>localStorage.getItem('frontier-demo.save.v1')),'legacy sentinel');});
 // Review views use a test-only saved character; production state stays entirely native.
 await page.evaluate(ch=>{Object.assign(__frontier.game.ch,ch);__frontier.game.refresh();__frontier.hud.el.frame.querySelector('.pname').textContent=ch.name;},character);
 for(const viewport of [{width:1440,height:900},{width:1180,height:820},{width:844,height:390}]){
  await page.setViewportSize(viewport);await page.waitForTimeout(80);await page.evaluate(()=>__loadoutReviewDraw(0,performance.now()/1000,{}));
  for(const view of ['equipment','skills','mods','materials']){
   await open(view==='equipment'||view==='materials'?'bag':view==='mods'?'mods':'skills');
   if(view==='materials')await tap('[data-action="bag-category"][data-id="material"]');else if(view==='equipment')await tap('[data-action="bag-category"][data-id="gear"]');
   await page.waitForFunction(()=>[...document.querySelectorAll('#atelier img')].every(i=>i.complete&&i.naturalWidth));await page.locator('#atelier img').evaluateAll(async images=>{await Promise.all(images.map(image=>image.decode()));});
   await check(`${view} ${viewport.width}x${viewport.height}: bounded windows and contained scrolling`,async()=>{
    const geo=await page.evaluate(()=>{const rect=e=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y,right:r.right,bottom:r.bottom,width:r.width,height:r.height}};const windows=[...document.querySelectorAll('#atelier .window')],bag=document.querySelector('.bag-grid');return {windows:windows.map(rect),height:innerHeight,width:innerWidth,scroll:document.documentElement.scrollHeight,targets:[...document.querySelectorAll('#atelier button')].filter(e=>e.getClientRects().length).map(rect),bag:bag?{capacity:+bag.dataset.pageSize,slots:bag.children.length,columns:getComputedStyle(bag).gridTemplateColumns.split(' ').length,rows:getComputedStyle(bag).gridTemplateRows.split(' ').length}:null};});
    assert.ok(geo.windows[1].x-geo.windows[0].right>=40);assert.ok(geo.windows.every(r=>r.x>0&&r.y>0&&r.right<geo.width&&r.bottom<geo.height));assert.ok(geo.scroll<=geo.height);assert.ok(geo.targets.every(r=>r.width>=43.5&&r.height>=43.5),'usable touch targets without scaling');
    if(geo.bag){assert.equal(geo.bag.columns,viewport.height<=520?5:6);assert.equal(geo.bag.rows,2);assert.equal(geo.bag.capacity,viewport.height<=520?10:12);assert.equal(geo.bag.slots,geo.bag.capacity);}
    await page.locator('#atelier .selection-shelf').scrollIntoViewIfNeeded();assert.ok(await page.locator('#atelier [data-action="details"]').isVisible());geometry.push({view,viewport,...geo});
   });
   await page.locator('#atelier .art>img').evaluateAll(async es=>{await Promise.all(es.map(i=>i.decode()));});
   await page.screenshot({path:`${out}/${view}-${viewport.width===844?'phone':viewport.width===1180?'tablet':'desktop'}.png`});
  }
 }
 await check('portrait supports both panes and focus without a rotate gate',async()=>{await page.setViewportSize({width:390,height:844});await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await page.evaluate(()=>__loadoutReviewDraw(0,performance.now()/1000,{}));await open('bag');assert.equal(await page.locator('.two-windows').isVisible(),true);assert.equal(await page.locator('.rotate-message').isVisible(),false);await tap('[data-action="view-side"][data-id="right"]');assert.equal(await page.locator('.library-window').isVisible(),true);await page.screenshot({path:out+'/equipment-portrait.png'});await tap('[data-action="view-side"][data-id="left"]');assert.equal(await page.locator('.character-window').isVisible(),true);await page.screenshot({path:out+'/character-portrait.png'});await page.setViewportSize({width:844,height:390});});
 await check('empty material/mod categories remain usable',async()=>{await page.evaluate(()=>{__frontier.game.ch.materials={};__frontier.game.ch.mods=[];for(const s of __frontier.game.ch.slots)s.mods=[];__frontier.game.refresh();});await open('mods');assert.match(await page.locator('.selection-shelf').innerText(),/ยังไม่มีเหรียญ/);await open('bag');await tap('[data-action="bag-category"][data-id="material"]');assert.match(await page.locator('.selection-shelf').innerText(),/ยังไม่มีวัตถุดิบ/);});
 await check('temporary avatar resources stabilize across gear changes',async()=>{
  await page.evaluate(()=>{const f=__frontier;f.panels.open('bag');f.panels.loadout.root.querySelector('[data-action="bag-category"][data-id="gear"]').click();});
  const first=character.gear.find(i=>i.base==='rusty_sword')?.uid||character.gear[0].uid,second=character.gear.find(i=>i.base==='tusk_blade').uid;
  const equip=async uid=>{await tap(`[data-action="item"][data-id="${uid}"]`);if(await page.locator('#atelier [data-action="equip"]:enabled').count())await tap('#atelier [data-action="equip"]:enabled');await page.waitForTimeout(700);};
  await equip(first);await equip(second);const before=await page.evaluate(()=>({...__frontier.view.renderer.info.memory}));
  for(let i=0;i<6;i++)await equip(i%2?second:first);
  const after=await page.evaluate(()=>({...__frontier.view.renderer.info.memory}));assert.deepEqual(after,before);await fs.writeFile(`${out}/avatar-resources.json`,JSON.stringify({before,after,cycles:6},null,2));
 });
 assert.deepEqual(errors,[]);checks.push('no JavaScript/console errors');
 await fs.writeFile(`${out}/report.json`,JSON.stringify({engine:engineName,interactionViewport,source:'actual game and persisted save; touch simulation',capture:engineName==='webkit'?'Native continuous world rendering; simulation and UI remain native':'existing freezeScene helper holds the completed world frame; simulation and UI remain native',checks,errors,geometry},null,2));console.log(`COMPLETE ${checks.length} checks`);
}catch(error){console.log('FAILURE',String(error),'ERRORS',errors);await page.screenshot({path:`${out}/failure.png`});if(await page.evaluate(()=>!!__frontier?.panels))console.log('UI STATE',(await state()).ui);throw error;}finally{await browser.close();}
