// Run against a local dev server: ICON_TEST_URL=http://localhost:4195 CHROMIUM_EXECUTABLE=/usr/bin/chromium node tests/browser/raster-icons.mjs
import {chromium} from 'playwright';import fs from 'node:fs';import assert from 'node:assert/strict';const out=new URL('./out/raster-icons/',import.meta.url).pathname;fs.mkdirSync(out,{recursive:true});const origin=process.env.ICON_TEST_URL||'http://localhost:4195';(async()=>{const b=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE,args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']}),p=await b.newPage({viewport:{width:1180,height:820},hasTouch:true});const errors=[],bad=[];p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.url().includes('/assets/icons/')&&r.status()!==200)bad.push(r.status())});await p.goto(origin+'/?fresh=1&quality=low');await p.waitForFunction(()=>window.__frontier?.game,null,{timeout:60000});await p.evaluate(()=>{let f=__frontier,g=f.game;f.paused=true;for(const s in g.ch.stats)g.ch.stats[s]=30;for(const id of Object.keys(g.data.items.gearBases).filter(id=>!g.ch.gear.some(x=>x.base===id)))g.ch.gear.push({uid:g.ch.nextUid++,base:id,grade:'C',upgrade:0,options:[]});for(const id of Object.keys(g.data.skills.combat))g.ch.skills[id]=1;g.ch.movementSkills=Object.keys(g.data.skills.movement);for(const id of Object.keys(g.data.mods.mods))g.ch.mods.push({uid:g.ch.nextUid++,id,level:1});for(const id of Object.keys(g.data.items.materials))g.ch.materials[id]=30;g.refresh()});
const nativeSizes=new Map(JSON.parse(fs.readFileSync(new URL('../../docs/icon-assets-manifest.json',import.meta.url),'utf8')).verified_assets.map(a=>[a.key,a.dimensions]));
const checked=[];async function decode(label){const imgs=await p.locator('.art>img').evaluateAll(async es=>{await Promise.all(es.map(e=>e.decode()));return es.map(e=>({key:e.parentElement.dataset.art,w:e.naturalWidth,h:e.naturalHeight}))});for(const i of imgs)assert.deepEqual([i.w,i.h],nativeSizes.get(i.key),label+'/'+i.key);checked.push({label,images:imgs.length});}
for(const v of ['bag','skills','mods','movement','growth','craft','journal','map']){await p.evaluate(v=>__frontier.panels.open(v),v);await decode(v);await p.screenshot({path:out+'raster-'+v+'-desktop.png'});}
for(const cat of ['gear','materials','mods']){await p.evaluate(cat=>{__frontier.panels.sel.bag=cat;__frontier.panels.open('bag')},cat);await decode('bag/'+cat);await p.screenshot({path:out+'raster-bag-'+cat+'.png'})}
for(const cat of ['weapon','armor','charm','skill','movement','mod']){await p.evaluate(cat=>{__frontier.panels.sel.craft=cat;__frontier.panels.open('craft')},cat);await decode('craft/'+cat);await p.screenshot({path:out+'raster-craft-'+cat+'.png'})}
for(const slot of ['weapon','armor','helm','boots','charm']){await p.evaluate(slot=>{const f=__frontier;f.panels.sel.bag='gear';f.panels.sel.gear=slot;f.panels.open('bag')},slot);await decode('equipment/'+slot);await p.screenshot({path:out+'raster-equipment-'+slot+'.png'});}
await p.evaluate(()=>{const f=__frontier;f.panels.sel.craftRecipe='wisp_staff';f.panels.sel.craftHistory={wisp_staff:[f.game.ch.gear.find(x=>x.base==='wisp_staff').uid]};f.panels.open('craft')});await decode('craft detail/results');await p.screenshot({path:out+'raster-craft-desktop.png'});
const hud=await p.evaluate(async()=>{const f=__frontier,g=f.game;f.panels.close();const results=[];for(const [kind,defs]of [['combat',g.data.skills.combat],['movement',g.data.skills.movement]])for(const id of Object.keys(defs)){if(kind==='combat')g.ch.slots[0]={skill:id,mods:[]};else g.ch.movement=id;g.refresh();f.input.refreshButtons();const button=kind==='combat'?f.input.buttons[0]:f.input.moveBtn,img=button.querySelector('.art>img');if(!img)throw Error('missing raster '+id);await img.decode();const r=img.getBoundingClientRect(),br=button.getBoundingClientRect();if(r.width<16||r.left<br.left||r.right>br.right+.5||r.top<br.top||r.bottom>br.bottom+.5)throw Error('clipped '+id);results.push(id)}return results});assert.equal(hud.length,17);
await p.setViewportSize({width:844,height:390});await p.screenshot({path:out+'raster-hud-phone.png'});await p.evaluate(()=>__frontier.panels.open('skills'));await decode('phone skills');await p.screenshot({path:out+'raster-skills-phone.png'});
await p.setViewportSize({width:1180,height:820});
const loot=await p.evaluate(async()=>{
 const {dropSprite}=await import('/src/render/dropart.js');const f=__frontier,g=f.game;f.panels.close();const ids=Object.keys(g.data.items.materials),pairs=ids.map(id=>[id,dropSprite(id),dropSprite(id)]);
 for(let i=0;pairs.some(([,s])=>!s.material.map.image?.complete)&&i<200;i++)await new Promise(r=>setTimeout(r,25));
 for(const[id,a,b]of pairs){if(a.material!==b.material||a.material.map!==b.material.map)throw Error('loot cache missed '+id);if(!a.material.userData.shared||!a.material.map.image?.naturalWidth)throw Error('loot image missing '+id);if(!a.material.map.image.src.includes('/assets/icons/material/'))throw Error('loot still SVG '+id);}
 const materials=new Set(pairs.map(([,s])=>s.material)),maps=new Set(pairs.map(([,s])=>s.material.map));
 const startX=g.player.x,startZ=g.player.z;g.drops=ids.map((item,i)=>({id:5000+i,item,n:1,x:startX+(i%6-2.5)*1.5,z:startZ+(Math.floor(i/6)-1.5)*1.5}));f.view.syncDrops(0,g.time+1);
 return {ids,uniqueMaterials:materials.size,uniqueTextures:maps.size,sprites:pairs.length*2,allDecoded:true};
});assert.equal(loot.uniqueTextures,22);await p.screenshot({path:out+'raster-ground-loot.png'});
const cleanup=await p.evaluate(async()=>{const f=__frontier,{dropSprite}=await import('/src/render/dropart.js');const ids=Object.keys(f.game.data.items.materials),cached=ids.map(id=>dropSprite(id).material);f.game.drops=[];f.view.syncDrops(0,f.game.time+2);if(f.view.dropViews.size!==0)throw Error('drop scene cleanup failed');return {removedAll:true,sharedMaterialsReused:ids.every((id,i)=>dropSprite(id).material===cached[i])}});assert.equal(cleanup.sharedMaterialsReused,true);
await p.goto(origin+'/data/items.json');await p.setViewportSize({width:1180,height:2800});
await p.evaluate(async()=>{const {art}=await import('/src/ui/art.js'),{RASTER_ICONS}=await import('/src/ui/raster-icons.js');document.body.innerHTML='<main style="background:#e7e9df;padding:20px;color:#243a37;font:12px Arial"><h2>Registered supplied PNGs</h2><section style="display:grid;grid-template-columns:repeat(6,1fr);gap:12px">'+Object.keys(RASTER_ICONS).map(key=>{const[k,id]=key.split('/');return '<div style="background:#f9f8f1;text-align:center;padding:8px">'+art(k,id)+'<p>'+key+'</p></div>'}).join('')+'</section></main>';const style=document.createElement('style');style.textContent='.art{width:140px;height:140px}.art>img{width:100%;height:100%;object-fit:contain}';document.head.append(style);await Promise.all([...document.images].map(i=>i.decode()))});await p.screenshot({path:out+'raster-contact-sheet.png',fullPage:true});
assert.deepEqual(errors,[]);assert.deepEqual(bad,[]);fs.writeFileSync(out+'raster-browser-report.json',JSON.stringify({checked,hud,loot,cleanup,errors,bad,engine:'Chromium',webkit:'not installed'},null,2));console.log(JSON.stringify({checked,hudCount:hud.length,loot,errors,bad}));await b.close()})();
