import {freezeScene} from './freeze-scene.mjs';
// Focused real Game+Panels capture; optional live renderer via LINE_URL.
import assert from 'node:assert/strict';
import {chromium,webkit} from 'playwright';
import {build} from 'vite';
import {readFileSync,mkdirSync,writeFileSync} from 'node:fs';
const out=process.env.LINE_OUT||new URL('./out/skill-lines/',import.meta.url).pathname;mkdirSync(out,{recursive:true});
const live=process.env.LINE_URL,engine=process.env.BROWSER==='webkit'?webkit:chromium;
let code='',css='';if(!live){const b=await build({configFile:false,logLevel:'error',build:{write:false,minify:false,lib:{entry:new URL('./workspace-harness.js',import.meta.url).pathname,name:'LineIntegration',formats:['iife']}}});code=b[0].output.find(f=>f.type==='chunk').code;css=['style','ux','art','workspaces','minimal','journal','overlays','fieldhud','skill-journal/journal','loadout-workspace'].map(n=>readFileSync(new URL('../../src/ui/'+n+'.css',import.meta.url),'utf8')).join('\n');for(const w of [400,600])css+=`@font-face{font-family:AtlasThai;src:url(data:font/ttf;base64,${readFileSync(new URL(`../../src/ui/skill-journal/fonts/noto-thai-${w}.ttf`,import.meta.url)).toString('base64')});font-weight:${w}}`;}
const browser=await engine.launch({executablePath:engine===chromium?process.env.CHROMIUM_EXECUTABLE:undefined,args:engine===chromium?['--no-sandbox',...(live?['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']:[])]:[]});const reports=[];
try{for(const [label,width,height,touch] of [['desktop',1440,900,false],['ipad',1180,820,true],['phone',390,844,true]]){
 if(process.env.LINE_CASES&&!process.env.LINE_CASES.split(',').includes(label))continue;
 const ctx=await browser.newContext({viewport:{width,height},hasTouch:touch,isMobile:touch,reducedMotion:'reduce'}),page=await ctx.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(15000);
 if(live){await page.goto(live,{waitUntil:'domcontentloaded',timeout:60000});await page.waitForFunction(()=>window.__frontier?.game?.time>.2,null,{timeout:60000});await freezeScene(page);}else{await page.setContent('<!doctype html><html lang="th"><meta name="viewport" content="width=device-width,initial-scale=1"><body><div id="hud"></div></body></html>');await page.addStyleTag({content:css});await page.addScriptTag({content:code});}
 const tap=async sel=>{const el=page.locator(sel).first();await(touch?el.tap():el.click());};
 const settle=async()=>{await page.evaluate(()=>document.fonts.ready);await page.waitForTimeout(350);await page.waitForFunction(()=>!__frontier.panels.jobJournal.snapshot().camera.active);};
 const snap=()=>page.evaluate(()=>__frontier.panels.jobJournal.snapshot());
 const open=async(tier,place=null)=>{await page.evaluate(({tier,place})=>{const f=__frontier;f.panels.close();f.panels.journalState={tier,place,view:place?'path':'junction',coords:{},entries:[],memories:{},context:[]};f.panels.open('job');},{tier,place});await settle();};
 const screenshot=async name=>{await settle();await page.screenshot({path:out+label+'-'+name+'.png'});};
 const readable=async()=>{const r=await page.evaluate(()=>{const map=document.querySelector('#map').getBoundingClientRect(),es=[...document.querySelectorAll('#plane > [data-node]')].map(el=>{const r=el.getBoundingClientRect(),boxes=[...el.querySelectorAll('.node-caption b,.node-caption small')].map(n=>{const text=document.createRange();text.selectNodeContents(n);return text.getBoundingClientRect();}).filter(b=>b.width&&b.height),left=Math.min(...boxes.map(b=>b.left)),top=Math.min(...boxes.map(b=>b.top)),right=Math.max(...boxes.map(b=>b.right)),bottom=Math.max(...boxes.map(b=>b.bottom)),c={x:left,y:top,width:right-left,height:bottom-top,left,right,top,bottom};return {id:el.dataset.node,r:{x:r.x,y:r.y,w:r.width,h:r.height},c:{x:c.x,y:c.y,w:c.width,h:c.height},visible:r.top>=map.top&&c.bottom<=map.bottom&&c.left>=map.left&&c.right<=map.right,hit:el.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2))};});return es;});const visible=r.filter(n=>n.visible);assert.ok(visible.length,'readable nodes in viewport');for(const n of visible){assert.ok(n.r.w>=44&&n.r.h>=44&&n.hit,JSON.stringify(n));}for(let i=0;i<r.length;i++)for(let j=i+1;j<r.length;j++){const a=r[i].c,b=r[j].c;assert.ok(!(a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y),'caption overlap '+r[i].id+' '+r[j].id);}return visible.map(n=>n.id);};
 await page.evaluate(()=>Object.assign(__frontier.game.ch,{jobPoints:6,jobLevel:7,jobNodes:['origin']}));
 await open(3);const before=await snap();assert.equal(before.groups.length,12);assert.equal(await page.locator('[data-discipline^="fam."]').count(),0);
 // All line gateways are direct overview choices, paginated without family nesting.
 const seen=new Set();do{for(const id of await page.locator('[data-discipline]').evaluateAll(es=>es.map(e=>e.dataset.discipline)))seen.add(id);const next=page.locator('[data-junction-page="1"]');if(!await next.count()||await next.isDisabled())break;await tap('[data-junction-page="1"]');await settle();}while(true);
 assert.equal([...seen].filter(id=>id.startsWith('view.')).length,9);assert.equal((await snap()).points,before.points);
 await open(3);await screenshot('overview');
 await open(3,'view.physical.3');await readable();await screenshot('physical');
 const start=(await snap()).camera;await tap('[data-action="zoom-out"]');await settle();assert.ok((await snap()).camera.z>=1||width>760);await readable();
 if(touch&&engine===chromium){
  const cdp=await ctx.newCDPSession(page),r=await page.locator('#map').boundingBox(),x=r.x+r.width/2,y=r.y+r.height/2,old=(await snap()).camera.z;
  try{await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:x-30,y,id:1},{x:x+30,y,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x-58,y,id:1},{x:x+58,y,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await settle();assert.ok((await snap()).camera.z>old);assert.equal((await snap()).points,before.points);}finally{await cdp.detach();}
  await tap('[data-action="fit"]');await settle();await readable();
 }
 // Pan exposes later rows without zooming labels into collisions; the gesture never allocates.
 const rect=await page.locator('#map').boundingBox();if(touch&&engine===chromium){const cdp=await ctx.newCDPSession(page);try{await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:rect.x+rect.width*.72,y:rect.y+rect.height*.8,id:1}]});for(let i=1;i<=8;i++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:rect.x+rect.width*.72,y:rect.y+rect.height*(.8-.65*i/8),id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}finally{await cdp.detach();}}else{ await page.mouse.move(rect.x+rect.width*.72,rect.y+rect.height*.8);await page.mouse.down();await page.mouse.move(rect.x+rect.width*.72,rect.y+rect.height*.15,{steps:8});await page.mouse.up(); }await settle();assert.equal((await snap()).points,before.points);assert.ok((await snap()).camera.y>start.y);await readable();await screenshot('branches');
 assert.equal(await page.locator('[data-bridge]').count(),0);assert.deepEqual((await snap()).bridges,[]);
 await tap('[data-action="junction"]');await settle();assert.equal((await snap()).view,'junction');
 await open(5,'view.physical.5');await tap('[data-line-page="view.physical.mastery"]');await settle();assert.equal((await snap()).place,'view.physical.mastery');await readable();await screenshot('mastery');await tap('[data-line-page="view.physical.5"]');await settle();assert.equal((await snap()).place,'view.physical.5');
 await open(2,'view.speed.2');await readable();await screenshot('neutral-speed');
 for(const [tier,group] of [[2,'impact'],[2,'support'],[3,'flow'],[3,'guard']]){await open(tier,group);await screenshot('neutral-'+group);await readable();}
 // Start a later-page line with no spending in any other major group.
 await page.evaluate(()=>{const f=__frontier;f.panels.close();Object.assign(f.game.ch,{jobLevel:20,jobPoints:4,jobNodes:['origin']});});
 await open(2,'view.physical.2');await tap('[data-action="search"]');await page.locator('#node-search').fill('line.physical.2.join');await tap('[data-jump="line.physical.2.join"]');await settle();assert.equal((await snap()).preview.cost,4);assert.equal((await snap()).preview.can,true);await tap('[data-action="route-preview"]');assert.equal(await page.locator('[data-preview-node]').count(),4);assert.equal(await page.locator('[data-preview-node^="bridge."]').count(),0);await tap('[data-action="back-to-node"]');await screenshot('local-purchase');await tap('[data-action="learn"]');await settle();assert.equal((await snap()).points,0);assert.ok((await snap()).owned.every(id=>id==='origin'||id.startsWith('line.physical.2.')));
 const owned=(await snap()).owned;await tap('[data-action="exit"]');assert.equal(await page.evaluate(()=>__frontier.panels.isOpen),false);await open(2,'view.physical.2');assert.deepEqual((await snap()).owned,owned);await tap('[data-action="exit"]');
 assert.deepEqual(errors,[]);reports.push({label,width,height,engine:process.env.BROWSER||'chromium',source:live?'real game and renderer':'real Game+Panels',ok:true,gateways:[...seen],pageErrors:errors});writeFileSync(out+'report.json',JSON.stringify(reports,null,2));await ctx.close();console.log('PASS lines',label);
}}finally{await browser.close();}
