// Only list PNGs that have actually been supplied, verified and included.
// Unregistered IDs retain their existing authored SVG; never invent placeholders.
export const RASTER_ICONS = Object.freeze({
 "gear/beetle_maul": "assets/icons/gear/beetle_maul.png",
 "gear/crab_shield": "assets/icons/gear/crab_shield.png",
 "gear/beetle_buckler": "assets/icons/gear/beetle_buckler.png",
 "gear/crag_tower_shield": "assets/icons/gear/crag_tower_shield.png",
 "gear/hide_gloves": "assets/icons/gear/hide_gloves.png",
 "gear/shell_mitts": "assets/icons/gear/shell_mitts.png",
 "gear/wolf_grips": "assets/icons/gear/wolf_grips.png",
 "gear/wisp_wraps": "assets/icons/gear/wisp_wraps.png",
 "gear/crag_gauntlets": "assets/icons/gear/crag_gauntlets.png",
 "gear/shell_knife": "assets/icons/gear/shell_knife.png",
 "gear/tusk_club": "assets/icons/gear/tusk_club.png",
 "gear/tusk_greatblade": "assets/icons/gear/tusk_greatblade.png",
 "gear/tide_staff": "assets/icons/gear/tide_staff.png",
 "gear/wolfbite_sword": "assets/icons/gear/wolfbite_sword.png",
 "gear/venom_wand": "assets/icons/gear/venom_wand.png",
 "gear/hermit_cleaver": "assets/icons/gear/hermit_cleaver.png",
 "gear/spore_staff": "assets/icons/gear/spore_staff.png",
 "gear/fang_bow": "assets/icons/gear/fang_bow.png",
 "gear/frontier_kris": "assets/icons/gear/frontier_kris.png",
 "gear/moonleaf_wand": "assets/icons/gear/moonleaf_wand.png",
 "gear/ranger_axe": "assets/icons/gear/ranger_axe.png",
 "gear/knight_greatsword": "assets/icons/gear/knight_greatsword.png",
 "gear/tidecaller_staff": "assets/icons/gear/tidecaller_staff.png",
 "gear/dusk_longbow": "assets/icons/gear/dusk_longbow.png",
 "gear/kite_shield": "assets/icons/gear/kite_shield.png",
 "gear/ranger_coat": "assets/icons/gear/ranger_coat.png",
 "gear/ranger_hood": "assets/icons/gear/ranger_hood.png",
 "gear/brigand_gloves": "assets/icons/gear/brigand_gloves.png",
 "gear/trail_boots": "assets/icons/gear/trail_boots.png",
 "gear/fang_talisman": "assets/icons/gear/fang_talisman.png",
 "gear/stormglass_blade": "assets/icons/gear/stormglass_blade.png",
 "gear/wisp_stiletto": "assets/icons/gear/wisp_stiletto.png",
 "gear/lantern_wand": "assets/icons/gear/lantern_wand.png",
 "gear/thunder_maul": "assets/icons/gear/thunder_maul.png",
 "gear/galebreaker": "assets/icons/gear/galebreaker.png",
 "gear/highland_shield": "assets/icons/gear/highland_shield.png",
 "gear/gale_boots": "assets/icons/gear/gale_boots.png",
 "gear/oathblade": "assets/icons/gear/oathblade.png",
 "gear/ruin_fang": "assets/icons/gear/ruin_fang.png",
 "gear/relic_wand": "assets/icons/gear/relic_wand.png",
 "gear/skyrender_bow": "assets/icons/gear/skyrender_bow.png",
 "arrow/feather_arrow": "assets/icons/arrow/feather_arrow.png",
 "arrow/tusk_arrow": "assets/icons/arrow/tusk_arrow.png",
 "arrow/hawk_arrow": "assets/icons/arrow/hawk_arrow.png",
 "arrow/storm_arrow": "assets/icons/arrow/storm_arrow.png",
 "arrow/hunter_arrow": "assets/icons/arrow/hunter_arrow.png",

 "material/greyfang_mane": "assets/icons/material/greyfang_mane.png",
 "material/warden_horn": "assets/icons/material/warden_horn.png",
 "material/ancient_core": "assets/icons/material/ancient_core.png",
 "material/crab_shell": "assets/icons/material/crab_shell.png",
 "material/sea_pearl": "assets/icons/material/sea_pearl.png",
 "material/salt_gel": "assets/icons/material/salt_gel.png",
 "material/shore_feather": "assets/icons/material/shore_feather.png",
 "material/hermit_fragment": "assets/icons/material/hermit_fragment.png",
 "skill/ward": "assets/icons/skill/ward.png",
 "skill/war_cry": "assets/icons/skill/war_cry.png",
 "skill/healing_spring": "assets/icons/skill/healing_spring.png",
 "skill/spirit_wolf": "assets/icons/skill/spirit_wolf.png",
 "skill/dash": "assets/icons/skill/dash.png",
 "skill/roll": "assets/icons/skill/roll.png",
 "skill/blink": "assets/icons/skill/blink.png",
 "skill/leap": "assets/icons/skill/leap.png",
 "material/boar_hide": "assets/icons/material/boar_hide.png",
 "material/boar_tusk": "assets/icons/material/boar_tusk.png",
 "material/beetle_shell": "assets/icons/material/beetle_shell.png",
 "material/venom_gland": "assets/icons/material/venom_gland.png",
 "material/wisp_core": "assets/icons/material/wisp_core.png",
 "material/glow_dust": "assets/icons/material/glow_dust.png",
 "material/ruin_shard": "assets/icons/material/ruin_shard.png",
 "material/wolf_pelt": "assets/icons/material/wolf_pelt.png",
 "material/wolf_fang": "assets/icons/material/wolf_fang.png",
 "material/spore_sac": "assets/icons/material/spore_sac.png",
 "material/crag_stone": "assets/icons/material/crag_stone.png",
 "material/golem_heart": "assets/icons/material/golem_heart.png",
 "material/hawk_feather": "assets/icons/material/hawk_feather.png",
 "material/storm_quill": "assets/icons/material/storm_quill.png",
 "gear/tusk_charm": "assets/icons/gear/tusk_charm.png",
 "gear/wisp_pendant": "assets/icons/gear/wisp_pendant.png",
 "gear/spore_amulet": "assets/icons/gear/spore_amulet.png",
 "gear/feather_charm": "assets/icons/gear/feather_charm.png",
 "gear/golem_amulet": "assets/icons/gear/golem_amulet.png",
 "gear/ancient_ring": "assets/icons/gear/ancient_ring.png",
 "gear/pearl_pendant": "assets/icons/gear/pearl_pendant.png",
 "gear/leather_cap": "assets/icons/gear/leather_cap.png",
 "gear/beetle_helm": "assets/icons/gear/beetle_helm.png",
 "gear/spore_hood": "assets/icons/gear/spore_hood.png",
 "gear/feather_circlet": "assets/icons/gear/feather_circlet.png",
 "gear/horned_helm": "assets/icons/gear/horned_helm.png",
 "gear/crabshell_helm": "assets/icons/gear/crabshell_helm.png",
 "gear/wolf_boots": "assets/icons/gear/wolf_boots.png",
 "gear/wisp_slippers": "assets/icons/gear/wisp_slippers.png",
 "gear/crag_greaves": "assets/icons/gear/crag_greaves.png",
 "gear/tide_boots": "assets/icons/gear/tide_boots.png",
 "gear/hide_vest": "assets/icons/gear/hide_vest.png",
 "gear/shell_guard": "assets/icons/gear/shell_guard.png",
 "gear/wolfpelt_coat": "assets/icons/gear/wolfpelt_coat.png",
 "gear/storm_mantle": "assets/icons/gear/storm_mantle.png",
 "gear/crag_plate": "assets/icons/gear/crag_plate.png",
 "gear/tusk_blade": "assets/icons/gear/tusk_blade.png",
 "gear/hunter_bow": "assets/icons/gear/hunter_bow.png",
 "gear/fang_dagger": "assets/icons/gear/fang_dagger.png",
 "gear/spore_wand": "assets/icons/gear/spore_wand.png",
 "gear/crag_axe": "assets/icons/gear/crag_axe.png",
 "gear/storm_bow": "assets/icons/gear/storm_bow.png",
 "gear/greyfang_sabre": "assets/icons/gear/greyfang_sabre.png",
 "gear/horn_greatblade": "assets/icons/gear/horn_greatblade.png",
 "gear/ancient_staff": "assets/icons/gear/ancient_staff.png",
 "skill/slash": "assets/icons/skill/slash.png",
 "skill/whirl_blade": "assets/icons/skill/whirl_blade.png",
 "skill/hunter_shot": "assets/icons/skill/hunter_shot.png",
 "skill/firebolt": "assets/icons/skill/firebolt.png",
 "skill/chain_spark": "assets/icons/skill/chain_spark.png",
 "skill/stone_burst": "assets/icons/skill/stone_burst.png",
 "skill/frost_nova": "assets/icons/skill/frost_nova.png",
 "skill/venom_mire": "assets/icons/skill/venom_mire.png",
 "skill/hex": "assets/icons/skill/hex.png",
 "gear/rusty_sword": "assets/icons/gear/rusty_sword.png",
 "gear/old_bow": "assets/icons/gear/old_bow.png",
 "gear/apprentice_staff": "assets/icons/gear/apprentice_staff.png",
 "gear/travel_tunic": "assets/icons/gear/travel_tunic.png",
 "gear/travel_boots": "assets/icons/gear/travel_boots.png",
 "gear/wisp_staff": "assets/icons/gear/wisp_staff.png"
});
export const EXPECTED_RASTER_KEYS = Object.freeze(["gear/beetle_maul", "gear/crab_shield", "gear/beetle_buckler", "gear/crag_tower_shield", "gear/hide_gloves", "gear/shell_mitts", "gear/wolf_grips", "gear/wisp_wraps", "gear/crag_gauntlets", "gear/shell_knife", "gear/tusk_club", "gear/tusk_greatblade", "gear/tide_staff", "gear/wolfbite_sword", "gear/venom_wand", "gear/hermit_cleaver", "gear/spore_staff", "gear/fang_bow", "gear/frontier_kris", "gear/moonleaf_wand", "gear/ranger_axe", "gear/knight_greatsword", "gear/tidecaller_staff", "gear/dusk_longbow", "gear/kite_shield", "gear/ranger_coat", "gear/ranger_hood", "gear/brigand_gloves", "gear/trail_boots", "gear/fang_talisman", "gear/stormglass_blade", "gear/wisp_stiletto", "gear/lantern_wand", "gear/thunder_maul", "gear/galebreaker", "gear/highland_shield", "gear/gale_boots", "gear/oathblade", "gear/ruin_fang", "gear/relic_wand", "gear/skyrender_bow", "arrow/feather_arrow", "arrow/tusk_arrow", "arrow/hawk_arrow", "arrow/storm_arrow", "arrow/hunter_arrow", "gear/rusty_sword", "gear/old_bow", "gear/apprentice_staff", "gear/tusk_blade", "gear/hunter_bow", "gear/fang_dagger", "gear/wisp_staff", "gear/spore_wand", "gear/crag_axe", "gear/storm_bow", "gear/greyfang_sabre", "gear/horn_greatblade", "gear/ancient_staff", "gear/travel_tunic", "gear/hide_vest", "gear/shell_guard", "gear/wolfpelt_coat", "gear/storm_mantle", "gear/crag_plate", "gear/leather_cap", "gear/beetle_helm", "gear/spore_hood", "gear/feather_circlet", "gear/horned_helm", "gear/travel_boots", "gear/wolf_boots", "gear/wisp_slippers", "gear/crag_greaves", "gear/tusk_charm", "gear/wisp_pendant", "gear/spore_amulet", "gear/feather_charm", "gear/golem_amulet", "gear/ancient_ring", "gear/crabshell_helm", "gear/tide_boots", "gear/pearl_pendant", "material/boar_hide", "material/boar_tusk", "material/beetle_shell", "material/venom_gland", "material/wisp_core", "material/glow_dust", "material/ruin_shard", "material/wolf_pelt", "material/wolf_fang", "material/spore_sac", "material/crag_stone", "material/golem_heart", "material/hawk_feather", "material/storm_quill", "material/greyfang_mane", "material/warden_horn", "material/ancient_core", "material/crab_shell", "material/sea_pearl", "material/salt_gel", "material/shore_feather", "material/hermit_fragment", "skill/slash", "skill/whirl_blade", "skill/hunter_shot", "skill/firebolt", "skill/chain_spark", "skill/stone_burst", "skill/frost_nova", "skill/venom_mire", "skill/hex", "skill/ward", "skill/war_cry", "skill/healing_spring", "skill/spirit_wolf", "skill/dash", "skill/roll", "skill/blink", "skill/leap"]);
const allowed = new Set(EXPECTED_RASTER_KEYS);
export function rasterIconUrl(kind, id, registry = RASTER_ICONS, base = import.meta.env?.BASE_URL || '/') {
 const key = kind + '/' + id, path = registry[key];
 if (!allowed.has(key) || !path) return null;
 if (path !== `assets/icons/${key}.png`) throw new Error('Invalid raster icon path: ' + key);
 return base.replace(/\/?$/, '/') + path;
}
export function rasterIconMarkup(kind, id, className = '', registry = RASTER_ICONS) {
 const url = rasterIconUrl(kind, id, registry);
 if (!url) return null;
 return `<span class="art art-${kind} ${className}" data-art="${kind}/${id}" aria-hidden="true"><img src="${url}" width="128" height="128" alt="" decoding="async" draggable="false"></span>`;
}
