import{test}from'node:test';import assert from'node:assert/strict';import*as THREE from'three';
import{prepareGrassCulling,updateGrassVisibility}from'../../src/render/grass-culling.js';
test('grass keeps viewport-edge wind spheres and matching baked colours without rebuilding buffers',()=>{
 const g=new THREE.PlaneGeometry(.4,.8),mesh=new THREE.InstancedMesh(g,new THREE.MeshBasicMaterial(),3),m=new THREE.Matrix4();
 for(const[i,x]of[0,30,10.25].entries())mesh.setMatrixAt(i,m.makeTranslation(x,0,0));
 g.setAttribute('aGrassBase',new THREE.InstancedBufferAttribute(new Uint8Array([10,11,12,20,21,22,30,31,32]),3,true));
 mesh.userData.grassRadii=new Float32Array([.5,.5,.5]);mesh.computeBoundingSphere();mesh.updateMatrixWorld(true);
 const bounds=mesh.boundingSphere.clone(),matrixArray=mesh.instanceMatrix.array,colorArray=g.attributes.aGrassBase.array;
 prepareGrassCulling(mesh);
 const camera=new THREE.PerspectiveCamera(90,1,.1,100);camera.position.set(0,0,10);camera.lookAt(0,0,0);camera.updateMatrixWorld(true);
 updateGrassVisibility(mesh,camera);
 assert.equal(mesh.count,2,'keep whole clump at viewport edge including wind');
 assert.deepEqual([...colorArray.slice(0,6)],[10,11,12,30,31,32]);assert.equal(matrixArray[28],10.25);
 const version=mesh.instanceMatrix.version;
 updateGrassVisibility(mesh,camera);assert.equal(mesh.instanceMatrix.version,version,'fixed camera skips buffer updates');
 camera.position.set(30,0,10);camera.lookAt(30,0,0);camera.updateMatrixWorld(true);updateGrassVisibility(mesh,camera);
 assert.equal(mesh.count,1);assert.equal(matrixArray[12],30);assert.deepEqual([...colorArray.slice(0,3)],[20,21,22]);
 mesh.userData.grassCulling.enabled=false;updateGrassVisibility(mesh,camera);
 assert.equal(mesh.count,3);assert.deepEqual([...colorArray],[10,11,12,20,21,22,30,31,32]);
 assert.equal(mesh.instanceMatrix.array,matrixArray);assert.equal(g.attributes.aGrassBase.array,colorArray);assert.ok(mesh.boundingSphere.equals(bounds));
 g.dispose();mesh.material.dispose();
});
