// One-shot correctness check of the real hosted game. No fixtures or performance verdicts.
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {resolve,join} from 'node:path';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
const BASE='https://pr80-ab-device-test-20261006.vercel.app/';
const SHAS={baseline:'1c6d2269d40f5e0524de13c6c5c5b1e2e4e56c0c',candidate:'08bf5cbb4bcd7b93f1b466ee88db79f1b347ee24'};
const UI='351930e7d051064f149e3d19964ea56d27bf6f6b46b5feabf60a1f595fef9182';
const out=resolve(process.env.EVIDENCE||'/tmp/pr80-live-check');await mkdir(out,{recursive:true});
const log=(...a)=>console.log(new Date().toISOString(),...a);
const save=(file,data)=>writeFile(join(out,file),typeof data==='string'?data:JSON.stringify(data,null,2));
const digest=b=>createHash('sha256').update(b).digest('hex');
async function get(path){const url=new URL(path,BASE);assert.equal(url.origin,new URL(BASE).origin);const r=await fetch(url,{redirect:'manual',signal:AbortSignal.timeout(30000)});if(r.status!==200)throw Error(`Anonymous GET ${url.pathname}: HTTP ${r.status}; redirect=${(r.headers.get('location')||'').split('?')[0]}`);return {bytes:Buffer.from(await r.arrayBuffer()),type:r.headers.get('content-type')};}
async function preflight(){const home=await get('');assert.match(home.bytes.toString(),/device-launcher/);const kit=JSON.parse((await get('kit.json')).bytes);assert.deepEqual(kit.sources,SHAS);assert.equal(kit.uiSha256,UI);assert.equal(digest((await get('ui.mjs')).bytes),UI);for(const v of Object.keys(SHAS)){const manifest=JSON.parse((await get(v+'/profile-source.json')).bytes);assert.equal(manifest.source,SHAS[v]);assert.equal(manifest.recorderSha256,kit.recorderSha256);await save(v+'-source.json',manifest);}await save('preflight.json',{ok:true,anonymous:true,base:BASE,kit,at:new Date().toISOString()});log('Anonymous preflight PASS');}
if(process.argv.includes('--preflight')){try{await preflight();}catch(e){await save('preflight-error.txt',e.stack);throw e;}}else{
const report={base:BASE,source:SHAS,workflowSha:process.env.GITHUB_SHA,runId:process.env.GITHUB_RUN_ID,runAttempt:process.env.GITHUB_RUN_ATTEMPT,purpose:'Correctness only; no hardware-performance comparison; real production builds, no mocks',settings:{viewport:[1180,820],dpr:1,quality:'medium',seed:4,streamBudget:6,dynres:0},cases:[],ok:false};
try{
 await preflight();const manifest=(await get('SHA256SUMS.txt')).bytes.toString();await save('host-SHA256SUMS.txt',manifest);
 const entries=manifest.trim().split('\n').map(line=>{const m=line.match(/^([a-f0-9]{64})  (.+)$/);assert(m);assert(!m[2].includes('..'));return {sha256:m[1],path:m[2]};});
 const audited=[];let cursor=0;await Promise.all(Array.from({length:4},async()=>{while(cursor<entries.length){const e=entries[cursor++],f=await get(e.path);assert.equal(digest(f.bytes),e.sha256,'Hosted bytes differ: '+e.path);if(/\.(?:mjs|js)$/.test(e.path))assert.match(f.type||'',/javascript/);audited.push({...e,bytes:f.bytes.length,type:f.type});}}));
 await save('asset-audit.json',{ok:true,files:audited.length,totalBytes:audited.reduce((n,e)=>n+e.bytes,0),filesChecked:audited.sort((a,b)=>a.path.localeCompare(b.path))});log('Hosted asset checksums PASS',audited.length);
 const {chromium,webkit}=await import('playwright');
 for(const engine of ['chromium','webkit']){
  const browser=await ({chromium,webkit})[engine].launch({headless:true,...(engine==='chromium'?{args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']}:{})});
  try{for(const [variant,run] of [['baseline',1],['candidate',2]]){
   const dir=join(out,engine+'-'+variant);await mkdir(dir,{recursive:true});const result={engine,variant,sha:SHAS[variant],ok:false,startedAt:new Date().toISOString(),errors:[],failedRequests:[],badResponses:[]};report.cases.push(result);
   const context=await browser.newContext({viewport:{width:1180,height:820},deviceScaleFactor:1,hasTouch:true,locale:'th-TH',acceptDownloads:true});const page=await context.newPage();page.setDefaultTimeout(30000);
   let closing=false;const requests=new Map();page.on('request',r=>requests.set(r.url(),{url:r.url(),type:r.resourceType()}));page.on('requestfinished',r=>{const e=requests.get(r.url());if(e)e.finished=true;});page.on('requestfailed',r=>{if(!closing)result.failedRequests.push({url:r.url(),error:r.failure()?.errorText});});page.on('response',r=>{if(r.status()>=400)result.badResponses.push({url:r.url(),status:r.status()});});page.on('pageerror',e=>result.errors.push({kind:'pageerror',message:String(e)}));page.on('console',m=>{if(m.type()==='error')result.errors.push({kind:'console',message:m.text()});});
   const state=()=>page.evaluate(()=>{const f=window.__frontier,p=window.__streamProfile,host=[...document.querySelectorAll('aside')].find(e=>e.shadowRoot?.getElementById('capture')),s=host?.shadowRoot;return {url:location.href,title:document.title,models:!!f?.modelsReady,game:!!f?.game,recorder:!!p,world:f?.world?.data?.id,building:f?.view?[...f.view.neighbours.values()].filter(n=>n.steps).length:null,activeLoads:p?.activeLoads,ready:s?s.getElementById('capture').disabled===false:false,text:s?.getElementById('live').textContent};});
   async function ready(){const deadline=Date.now()+480000;let last=0;while(Date.now()<deadline){const s=await state();if(Date.now()-last>30000){log(engine,variant,JSON.stringify(s));last=Date.now();}if(s.ready)return s;if(result.errors.length||result.failedRequests.length||result.badResponses.length)throw Error('Runtime/network error before imported-ready');await page.waitForTimeout(1000);}throw Error('Imported-ready not reached within 480 seconds; no retries or altered streaming budget');}
   try{
    log('START actual game',engine,variant);await page.goto(BASE,{waitUntil:'domcontentloaded',timeout:30000});await page.locator('input[name="device"]').fill('Actions '+engine+' software-GPU correctness only');await page.locator('input[name="group"]').fill('live-'+process.env.GITHUB_RUN_ID);await page.locator('#runs button').nth(run-1).click();await page.waitForURL(new RegExp('/'+variant+'/\\?'),{waitUntil:'domcontentloaded',timeout:30000});
    result.importedReady=await ready();assert(result.importedReady.game&&result.importedReady.models&&result.importedReady.recorder);assert.equal(new URL(page.url()).searchParams.get('streamBudget'),'6');
    await page.locator('#open').tap();await page.locator('#phase').selectOption('quiet-after-load');await page.locator('#mark').tap();await page.waitForTimeout(10000);await page.keyboard.down('w');await page.waitForTimeout(750);await page.keyboard.up('w');
    await ready();result.scene=await page.evaluate(()=>{const f=window.__frontier,view=f.view;const meshes=o=>{let n=0;o?.traverse(e=>{if(e.isMesh)n++;});return n;};return {modelsReady:f.modelsReady,world:f.world.data.id,player:{x:f.game.player.x,z:f.game.player.z},quality:view.quality,budget:view.streamBudgetMs,contextLost:view.renderer.getContext().isContextLost(),drawCalls:view.renderer.info.render.calls,regions:[view.region,...[...view.neighbours.values()].map(n=>n.region)].filter(Boolean).map(r=>({world:r.world.data.id,disposed:r.disposed,meshCount:meshes(r.root),cityExpected:!!r.world.data.city?.enabled,cityMeshes:meshes(r.cityRoot),kitMeshes:meshes(r.townKitRoot),npcCount:r.npcs.length,grassCount:r.grass.length,stats:r.stats}))};});
    assert.equal(result.scene.budget,6);assert.equal(result.scene.quality,'medium');assert.equal(result.scene.contextLost,false);assert(result.scene.drawCalls>0);for(const r of result.scene.regions){assert(!r.disposed);assert(r.meshCount>0);assert(r.npcCount>=2);if(r.cityExpected)assert(r.cityMeshes>0,'Expected city missing');}
    await page.screenshot({path:join(dir,'game-imported-ready.png')});await page.locator('#open').tap();await page.locator('#sample').tap();await page.locator('#capture').tap();await page.locator('#preview').waitFor({state:'visible',timeout:30000});const [png]=await Promise.all([page.waitForEvent('download'),page.locator('#png').click()]);await png.saveAs(join(dir,'canvas-imported-ready.png'));assert((await readFile(join(dir,'canvas-imported-ready.png'))).length>10000);
    await page.locator('#finish').tap();await page.locator('#result').waitFor({state:'visible'});const [download]=await Promise.all([page.waitForEvent('download'),page.locator('#download').tap()]);const jsonPath=join(dir,'actual-game-export.json');await download.saveAs(jsonPath);const raw=await readFile(jsonPath,'utf8'),data=JSON.parse(raw);
    assert.equal(data.schema,'pr80-device-v1');assert.equal(data.variant,variant);assert.equal(data.source.source,SHAS[variant]);assert.equal(data.kit.uiSha256,UI);assert.equal(data.requested.streamBudget,6);assert.equal(data.final.streamBudget,6);assert(data.measurement.readiness.ready);assert(data.profile.frames.length>=100,'Require real frame collection, not a 0-2-sample placeholder');assert(data.summary.samples>=100);assert(data.profile.events.length>0);assert(data.summary.regions.some(r=>r.importedReadyMs!==null));assert(data.annotations.some(a=>a.type==='phase-mark'));assert(data.annotations.some(a=>a.type==='manual-resource-sample'));assert.equal(data.summary.errors.length,0);
    await page.locator('#show').tap();assert.equal(await page.locator('#raw').inputValue(),raw);await page.screenshot({path:join(dir,'real-export-ui.png')});assert.equal(result.errors.length,0);assert.equal(result.failedRequests.length,0);assert.equal(result.badResponses.length,0);
    result.export={file:'actual-game-export.json',bytes:Buffer.byteLength(raw),sha256:digest(raw),frameSamples:data.summary.samples,stageLabels:data.summary.stages.map(e=>e.name),source:data.source.source,importedReady:true,validationIssues:data.validation.issues,notAHardwareBenchmark:true};result.ok=true;log('PASS actual game, imports, measurement controls and JSON',engine,variant);
   }catch(e){result.error=e.stack;try{result.diagnostic=await state();await page.screenshot({path:join(dir,'failure.png'),timeout:10000});await writeFile(join(dir,'body.html'),await page.content());}catch{}throw e;}finally{result.completedAt=new Date().toISOString();await writeFile(join(dir,'result.json'),JSON.stringify(result,null,2));await writeFile(join(dir,'requests.json'),JSON.stringify([...requests.values()],null,2));closing=true;await context.close();await save('results.json',report);}
  }}finally{await browser.close();}
 }
 report.ok=true;
}catch(e){report.error=e.stack;process.exitCode=1;log('STOP',e.stack);}finally{await save('results.json',report);}
}
