// Bake Meshy's walk and run clips (assets/meshy/hero_base/*_armature.glb) into driver-bone
// pose tables for HumanoidAnimator: data/gait.json. The clips play on the prepared hero base
// (render/skinned.js); each frame's skin-bone rotations are converted back to the procedural
// driver bones (the inverse of syncSkin), so the tables also drive the procedural NPC body.
// Usage: node scripts/bake-gait.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { prepareHeroBase, MAP, DRIVER } from '../src/render/skinned.js';

const root = new URL('../', import.meta.url);
const cfg = JSON.parse(readFileSync(new URL('data/models.json', root))).characters.hero_base;
const load = (path) => {
  const buf = readFileSync(new URL(path, root));
  return new Promise((ok, fail) => new GLTFLoader().parse(buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength), '', ok, fail));
};
const FRAMES = 24;
const r3 = (v) => Math.round(v * 1000) / 1000;

const base = await load('public/models/' + cfg.file.split('/').pop());
const T = prepareHeroBase(base, cfg);
const bones = {};
T.scene.traverse((o) => o.isBone && (bones[o.name] = o));
T.scene.updateMatrixWorld(true);
const offset = {};
for (const n of Object.keys(MAP)) offset[n] = bones[n].getWorldQuaternion(new THREE.Quaternion());
const skinOf = Object.fromEntries(Object.entries(MAP).map(([s, d]) => [d, s]));
const parentOf = Object.fromEntries(DRIVER);
const restHips = new THREE.Vector3(...T.joints.hips);

function bake(file) {
  return load(file).then((gltf) => {
    const clip = gltf.animations[0];
    const mixer = new THREE.AnimationMixer(T.scene);
    mixer.clipAction(clip).play();
    const frames = [];
    for (let f = 0; f < FRAMES; f++) {
      mixer.setTime((f / FRAMES) * clip.duration);
      T.scene.updateMatrixWorld(true);
      const world = { body: new THREE.Quaternion() };
      const local = {};
      for (const [d] of DRIVER) {
        if (d === 'body') continue;
        const s = skinOf[d];
        world[d] = bones[s].getWorldQuaternion(new THREE.Quaternion()).multiply(offset[s].clone().invert());
        const q = world[parentOf[d]].clone().invert().multiply(world[d]);
        local[d] = new THREE.Euler().setFromQuaternion(q).toArray().slice(0, 3);
      }
      const hips = bones.Hips.getWorldPosition(new THREE.Vector3()).sub(restHips);
      const foot = bones.LeftFoot.getWorldPosition(new THREE.Vector3());
      frames.push({ local, hips, foot });
    }
    // distance per cycle: root motion if the clip travels, else the planted foot's speed
    const dt = clip.duration / FRAMES;
    const travel = frames[FRAMES - 1].hips.z - frames[0].hips.z;
    let cycle;
    if (Math.abs(travel) > 0.2) cycle = Math.abs(travel) * (FRAMES / (FRAMES - 1));
    else {
      const minY = Math.min(...frames.map((f) => f.foot.y));
      const v = [];
      for (let f = 0; f < FRAMES; f++) {
        const a = frames[f], b = frames[(f + 1) % FRAMES];
        if (a.foot.y < minY + 0.02 && b.foot.y < minY + 0.02) v.push((a.foot.z - b.foot.z) / dt);
      }
      cycle = (v.reduce((x, y) => x + y, 0) / v.length) * clip.duration;
    }
    // start the cycle at the left heel strike (left foot furthest forward)
    const rel = frames.map((f) => f.foot.z - f.hips.z);
    const start = rel.indexOf(Math.max(...rel));
    const order = frames.map((_, i) => frames[(i + start) % FRAMES]);
    // remove forward travel and centre the side sway; keep the bob
    const mx = order.reduce((s, f) => s + f.hips.x, 0) / FRAMES;
    const bonesOut = {};
    for (const [d] of DRIVER) if (d !== 'body') bonesOut[d] = order.map((f) => f.local[d].map(r3));
    return {
      duration: r3(clip.duration),
      cycle: r3(cycle),
      speed: r3(cycle / clip.duration),
      body: order.map((f) => [r3(f.hips.x - mx), r3(f.hips.y), 0]),
      bones: bonesOut,
    };
  });
}

const out = {
  _note: 'Generated by scripts/bake-gait.mjs from Meshy walk/run clips. Driver-bone Euler XYZ rotations (radians) per frame, one gait cycle starting at the left heel strike; body = hips offset (m); cycle = metres travelled per cycle at speed m/s.',
  walk: await bake('assets/meshy/hero_base/walk_armature.glb'),
  run: await bake('assets/meshy/hero_base/run_armature.glb'),
};
writeFileSync(new URL('data/gait.json', root), JSON.stringify(out) + '\n');
console.log('walk', out.walk.cycle, 'm/cycle', out.walk.speed, 'm/s;', 'run', out.run.cycle, 'm/cycle', out.run.speed, 'm/s');
