// Writes the generated map layout (colliders, props, decoration, spawn points, waypoints) to
// data/generated/layout.json and the terrain heights to data/generated/heightmap.json, so
// another engine (Godot) can place the same world without re-implementing src/core/world.js.
import { mkdirSync, writeFileSync } from 'node:fs';
import { loadData } from '../src/core/data-node.js';
import { createWorld } from '../src/core/world.js';
import { Game } from '../src/core/game.js';

const data = loadData();
const world = createWorld(data.world);
const game = new Game(data, { seed: 1 });
const round = (v) => Math.round(v * 1000) / 1000;
const clean = (o) => JSON.parse(JSON.stringify(o, (k, v) => (typeof v === 'number' ? round(v) : v)));
const out = {
  _doc: 'Generated by scripts/export-layout.mjs from data/world.json. Axes: X right, Y up, Z south (Godot uses the same). Units: metres. Angles: radians about +Y.',
  worldId: data.world.id || 'frontier',
  harbor: data.world.harbor || null,
  bounds: world.bounds,
  waterLevel: world.waterLevel,
  bridges: world.bridges,
  docks: world.docks,
  safeRoutes: data.world.safeRoutes || [],
  waypoints: world.waypoints,
  zones: world.zones.map((z) => ({ id: z.id, name: z.name, rects: z.rects, level: z.level, safe: !!z.safe })),
  colliders: { circles: world.circles, boxes: world.boxes },
  decor: world.decor,
  spawns: game.spawnPoints.map((s) => ({ monster: s.monster, zone: s.zone, level: s.level, x: s.x, z: s.z, respawn: s.respawn, boss: !!s.boss })),
};
mkdirSync(new URL('../data/generated/', import.meta.url), { recursive: true });
writeFileSync(new URL('../data/generated/layout.json', import.meta.url), JSON.stringify(clean(out)));
const hf = world.heightfield;
writeFileSync(
  new URL('../data/generated/heightmap.json', import.meta.url),
  JSON.stringify({ _doc: 'Terrain height (metres) on a regular grid: height at (ox + i*res, oz + j*res) is data[j*w + i]. Godot: HeightMapShape3D / a MeshInstance3D.', ox: hf.ox, oz: hf.oz, res: hf.res, w: hf.w, h: hf.h, data: Array.from(hf.data, (v) => Math.round(v * 100) / 100) })
);
console.log(`heightmap: ${hf.w}x${hf.h} @ ${hf.res} m`);
console.log(`layout: ${world.circles.length} circles, ${world.boxes.length} boxes, ${out.spawns.length} spawns`);
