// Writes the generated map layout (colliders, props, decoration, spawn points) to
// data/generated/layout.json so another engine (Godot) can place the same world
// without re-implementing src/core/world.js.
import { mkdirSync, writeFileSync } from 'node:fs';
import { loadData } from '../src/core/data-node.js';
import { createWorld } from '../src/core/world.js';
import { Game } from '../src/core/game.js';

const data = loadData();
const world = createWorld(data.world);
const game = new Game(data, { seed: 1 });
const round = (v) => Math.round(v * 1000) / 1000;
const clean = (o) => JSON.parse(JSON.stringify(o, (k, v) => (typeof v === 'number' ? round(v) : v)));
const out = {
  _doc: 'Generated by scripts/export-layout.mjs from data/world.json. Axes: X right, Y up, Z south (Godot uses the same). Units: metres. Angles: radians about +Y.',
  bounds: world.bounds,
  bridge: world.bridgeBox,
  gateZ: world.gateZ,
  colliders: { circles: world.circles, boxes: world.boxes },
  decor: world.decor,
  spawns: game.spawnPoints.map((s) => ({ monster: s.monster, zone: s.zone, level: s.level, x: s.x, z: s.z, respawn: s.respawn, boss: !!s.boss })),
};
mkdirSync(new URL('../data/generated/', import.meta.url), { recursive: true });
writeFileSync(new URL('../data/generated/layout.json', import.meta.url), JSON.stringify(clean(out)));
console.log(`layout: ${world.circles.length} circles, ${world.boxes.length} boxes, ${out.spawns.length} spawns`);
